version: '3.9'

networks:
  muzShop-network:
    driver: bridge

services:
  app:
    container_name: muz-shop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - muzShop-network
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: "muzShop-db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
    ports:
      - "5433:5432"
    networks:
      - muzShop-network
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
