version: '3.9'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "muzShop-db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
    ports:
      - "5433:5432"

  testDatabase:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "test-muzShop-db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "testdbpassword"
    ports:
      - "5434:5432"